### ISSUE TITLE
java.net.ConnectException: Connection refused: connect

### ISSUE THREAD

**Issue by tschipunza** [openMF/DataImportTool#37]
Hello,

I'm getting an error saying " java.net.ConnectException: Connection refused: connect " when i try to download template, any suggestion?

**Comment by ronysaputro8** [comment]
hi, i have same error " java.net.ConnectException: Connection refused: connect "  when download template.
how to solve it?

tank u

**Comment by santoshconflux** [comment]
Please check you have written correct credentials in dataimport.properties file.

**Comment by ronysaputro8** [comment]
Thank u mr santoshmath.
dataimport.properties file location :  c:\users\administrtor\dataimport.properties

Mifos.endpoint=https://localhost:8443/mifosng-provider/api/v1/
Mifos.user.id=mifos
Mifos.password=password
Mifos.tenant.id=default

Like this in my pc.
I Need your advice please.
Thank

**Comment by santoshconflux** [comment]
In Mifos.endpoint, make it as fineract-provider in stead of mifosng-provider

Also check file extension. Sometimes, it might be dataimport.properties.txt, where .txt file extension may be hidden. if it's true, remove .txt and keep it as plain "dataimport.properties" . And also ensure , you are using gradle 2.6.

**Comment by ronysaputro8** [comment]
Ok... I will check it .
Thank u mr santosh

**Comment by ronysaputro8** [comment]
Dear mr santoshmath,
could you please send the complate pdf documentation.
Mifos x 16
Many thank for u

**Comment by santoshconflux** [comment]
There  is  online documentation. https://mifosforge.jira.com/wiki/display/docs/User+Manual

**Comment by ronysaputro8** [comment]
C:\gradle-2.6-all\gradle-2.6 - OK
dataimport.property ok no hide no other extention
![gradle26](https://cloud.githubusercontent.com/assets/28521275/26022804/932c19ec-37d8-11e7-98fb-7d4bc8c5e8ad.gif)
![gadle path](https://cloud.githubusercontent.com/assets/28521275/26022809/9ea888b4-37d8-11e7-8cb4-07688ce34f03.gif)
![dataimport file](https://cloud.githubusercontent.com/assets/28521275/26022811/a804e6d2-37d8-11e7-805a-613f528fd3e5.gif)
![dataimport file location](https://cloud.githubusercontent.com/assets/28521275/26022815/b385b31a-37d8-11e7-908f-c7443f057124.gif)
![dataimport content](https://cloud.githubusercontent.com/assets/28521275/26022816/b7655ad0-37d8-11e7-8057-5d6fc73930ce.gif)
![download template refused](https://cloud.githubusercontent.com/assets/28521275/26022818/ba366f10-37d8-11e7-9bdc-9e0dac45eb14.gif)

but when i select
 Download template to help facilitate Clients Import.
Select Client Type :   x Individual    Corporate 
click download it still show messege "java.net.ConnectException: Connection refused: connect".

.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketI
mpl.java:79)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.ja
va:345)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocket
Impl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java
:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:649)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173
)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewH
ttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConn
ection.java:1103)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConne
ction.java:997)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect
(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLCo
nnection.java:1511)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLCon
nection.java:1439)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480
)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Htt
psURLConnectionImpl.java:338)
        at org.openmf.mifos.dataimport.http.SimpleHttpResponse.getContent(Simple
HttpResponse.java:26)
        at org.openmf.mifos.dataimport.http.MifosRestClient.createAuthToken(Mifo
sRestClient.java:111)
        ... 21 more
java.lang.IllegalStateException: java.net.ConnectException: Connection refused:
connect
        at org.openmf.mifos.dataimport.http.MifosRestClient.createAuthToken(Mifo
sRestClient.java:115)
        at org.openmf.mifos.dataimport.populator.OfficeSheetPopulator.downloadAn
dParse(OfficeSheetPopulator.java:41)
        at org.openmf.mifos.dataimport.populator.client.CenterWorkbookPopulator.
downloadAndParse(CenterWorkbookPopulator.java:58)
        at org.openmf.mifos.dataimport.web.DownloadServiceServlet.downloadAndPop
ulate(DownloadServiceServlet.java:44)
        at org.openmf.mifos.dataimport.web.DownloadServiceServlet.doGet(Download
ServiceServlet.java:34)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:305)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperV
alve.java:222)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextV
alve.java:123)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(Authentica
torBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.j
ava:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.j
ava:99)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineVal
ve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.jav
a:408)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp
11Processor.java:1023)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(
AbstractProtocol.java:589)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoin
t.java:310)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketI
mpl.java:79)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.ja
va:345)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocket
Impl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java
:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:649)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173
)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewH
ttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConn
ection.java:1103)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConne
ction.java:997)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect
(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLCo
nnection.java:1511)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLCon
nection.java:1439)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480
)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Htt
psURLConnectionImpl.java:338)
        at org.openmf.mifos.dataimport.http.SimpleHttpResponse.getContent(Simple
HttpResponse.java:26)
        at org.openmf.mifos.dataimport.http.MifosRestClient.createAuthToken(Mifo
sRestClient.java:111)
        ... 21 more
java.lang.IllegalStateException: java.net.ConnectException: Connection refused:
connect
        at org.openmf.mifos.dataimport.http.MifosRestClient.createAuthToken(Mifo
sRestClient.java:115)
        at org.openmf.mifos.dataimport.populator.OfficeSheetPopulator.downloadAn
dParse(OfficeSheetPopulator.java:41)
        at org.openmf.mifos.dataimport.populator.client.ClientWorkbookPopulator.
downloadAndParse(ClientWorkbookPopulator.java:51)
        at org.openmf.mifos.dataimport.web.DownloadServiceServlet.downloadAndPop
ulate(DownloadServiceServlet.java:44)
        at org.openmf.mifos.dataimport.web.DownloadServiceServlet.doGet(Download
ServiceServlet.java:34)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:305)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperV
alve.java:222)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextV
alve.java:123)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(Authentica
torBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.j
ava:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.j
ava:99)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineVal
ve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.jav
a:408)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp
11Processor.java:1023)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(
AbstractProtocol.java:589)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoin
t.java:312)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketI
mpl.java:79)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.ja
va:345)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocket
Impl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java
:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:649)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173
)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewH
ttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConn
ection.java:1103)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConne
ction.java:997)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect
(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLCo
nnection.java:1511)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLCon
nection.java:1439)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480
)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Htt
psURLConnectionImpl.java:338)
        at org.openmf.mifos.dataimport.http.SimpleHttpResponse.getContent(Simple
HttpResponse.java:26)
        at org.openmf.mifos.dataimport.http.MifosRestClient.createAuthToken(Mifo
sRestClient.java:111)
        ... 21 more
java.lang.IllegalStateException: java.net.ConnectException: Connection refused:
connect
        at org.openmf.mifos.dataimport.http.MifosRestClient.createAuthToken(Mifo
sRestClient.java:115)
        at org.openmf.mifos.dataimport.populator.OfficeSheetPopulator.downloadAn
dParse(OfficeSheetPopulator.java:41)
        at org.openmf.mifos.dataimport.populator.client.ClientWorkbookPopulator.
downloadAndParse(ClientWorkbookPopulator.java:51)
        at org.openmf.mifos.dataimport.web.DownloadServiceServlet.downloadAndPop
ulate(DownloadServiceServlet.java:44)
        at org.openmf.mifos.dataimport.web.DownloadServiceServlet.doGet(Download
ServiceServlet.java:34)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:305)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperV
alve.java:222)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextV
alve.java:123)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(Authentica
torBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.j
ava:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.j
ava:99)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineVal
ve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.jav
a:408)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp
11Processor.java:1023)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(
AbstractProtocol.java:589)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoin
t.java:310)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketI
mpl.java:79)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.ja
va:345)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocket
Impl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java
:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:649)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173
)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewH
ttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConn
ection.java:1103)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConne
ction.java:997)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect
(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLCo
nnection.java:1511)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLCon
nection.java:1439)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480
)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Htt
psURLConnectionImpl.java:338)
        at org.openmf.mifos.dataimport.http.SimpleHttpResponse.getContent(Simple
HttpResponse.java:26)
        at org.openmf.mifos.dataimport.http.MifosRestClient.createAuthToken(Mifo
sRestClient.java:111)
        ... 21 more
> Building 85% > :tomcatRunWar


thank before..

**Comment by santoshconflux** [comment]
Send me contact request on Skype. santoshmath99. I will look into it by sharing  the screen. or through TeamViwer

**Comment by saliormoon** [comment]
OS: Windows
D:\jdk1.8\bin>java SSLPoke developer.nrel.gov 443
java.net.ConnectException: Connection timed out: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketI
mpl.java:79)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.ja
va:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocket
Impl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java
:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
        at sun.security.ssl.SSLSocketImpl.<init>(SSLSocketImpl.java:432)
        at sun.security.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryIm
pl.java:88)
        at SSLPoke.main(SSLPoke.java:25)
Anyone can help me?

**Comment by julwu** [comment]
I had this problem too and i edit directly in the file ApplicationContextListner.java the value my IP adress without port specifications. 

and comment as follow ; 
private void readAndSetAsSysProp(String key, String defaultValue, Properties prop) {
		String value = prop.getProperty(key);
		//if(!StringUtils.isBlank(value)) {
			//System.setProperty(key, value);
		//} else {
			System.setProperty(key, defaultValue);
		//}
	}

hope it will help

**Comment by karthikk74** [comment]
Hello,

I'm getting an error saying " java.net.ConnectException: Connection refused: connect " when i try to download template, any suggestion?
